// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8ezVBUfhxTZRVwYwN3N5yL
// Component: vuK03WDG9KmD
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 8ezVBUfhxTZRVwYwN3N5yL/projectcss
import sty from "./PlasmicReviews.module.css"; // plasmic-import: vuK03WDG9KmD/css
import Star1Icon from "./icons/PlasmicIcon__Star1"; // plasmic-import: 0JyQ0i6OVRYN/icon

createPlasmicElementProxy;

export const PlasmicReviews__VariantProps = new Array();

export const PlasmicReviews__ArgProps = new Array(
  "imageUrl",
  "name",
  "content",
  "rating",
  "createdAt"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReviews__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          name: "Anonymous",
          content: "...",
          createdAt: "2024-04-10T07:33:41.927Z"
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"review"}
      data-plasmic-override={overrides.review}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.review
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__zl7H9)}>
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"64px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"64px"}
          loading={"lazy"}
          src={(() => {
            try {
              return $props.imageUrl;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {
                  src: "/plasmic/website_starter/images/ellipse1.svg",
                  fullWidth: 64,
                  fullHeight: 64,
                  aspectRatio: 1
                };
              }
              throw e;
            }
          })()}
        />

        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___5CFbW)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__mze1C
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.name;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Freida Varnes";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__v4UY6
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return "Reviewed " + $props.createdAt + " months ago";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Review 1 months ago";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </Stack__>
        <div className={classNames(projectcss.all, sty.freeBox__tplkd)}>
          <Star1Icon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lty9Y
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.rating;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "5.0";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
      </div>
      {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
        (() => {
          try {
            return [
              {
                imageUrl: "",
                name: "",
                timeCreated: "",
                rating: 5,
                content: ""
              }
            ];
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [];
            }
            throw e;
          }
        })()
      ).map((__plasmic_item_0, __plasmic_idx_0) => {
        const currentItem = __plasmic_item_0;
        const currentIndex = __plasmic_idx_0;
        return (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__s0QhH
            )}
            key={currentIndex}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.content;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        );
      })}
    </div>
  );
}

const PlasmicDescendants = {
  review: ["review", "img", "svg"],
  img: ["img"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReviews__ArgProps,
          internalVariantPropNames: PlasmicReviews__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReviews__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "review") {
    func.displayName = "PlasmicReviews";
  } else {
    func.displayName = `PlasmicReviews.${nodeName}`;
  }
  return func;
}

export const PlasmicReviews = Object.assign(
  // Top-level PlasmicReviews renders the root element
  makeNodeComponent("review"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicReviews
    internalVariantProps: PlasmicReviews__VariantProps,
    internalArgProps: PlasmicReviews__ArgProps
  }
);

export default PlasmicReviews;
/* prettier-ignore-end */
