// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8ezVBUfhxTZRVwYwN3N5yL
// Component: 0bDiwzUEHDAP
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button from "../../Button"; // plasmic-import: Mk2LrAAMfItq/component
import Reviews from "../../Reviews"; // plasmic-import: vuK03WDG9KmD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 8ezVBUfhxTZRVwYwN3N5yL/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 0bDiwzUEHDAP/css
import Frame1000006008Icon from "./icons/PlasmicIcon__Frame1000006008"; // plasmic-import: 5gSvYEif6wmd/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <h1
            data-plasmic-name={"h1"}
            data-plasmic-override={overrides.h1}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.__wab_text,
              sty.h1
            )}
          >
            {"Reviews"}
          </h1>
          <section
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(projectcss.all, sty.main)}
          >
            <div
              data-plasmic-name={"overallReview"}
              data-plasmic-override={overrides.overallReview}
              className={classNames(projectcss.all, sty.overallReview)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__jCWu)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pH3Zd
                  )}
                >
                  {"5.0"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__g8Os6)}>
                  <Stack__
                    as={Frame1000006008Icon}
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p8Cxx
                    )}
                  >
                    {"1000 Reviews"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g6Cyh
                  )}
                >
                  {"Very Good"}
                </div>
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__lSu6I)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gCx
                  )}
                >
                  {"Write a Review"}
                </div>
              </Button>
            </div>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return [
                    {
                      imageUrl:
                        "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
                      name: "Freida Varnes",
                      rating: 5.0,
                      content:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
                      timeCreated: "1"
                    },
                    {
                      imageUrl:
                        "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBvcnRyYWl0fGVufDB8fDB8fHww",
                      name: "Marx Heshley",
                      rating: 4.0,
                      content:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
                      timeCreated: "2"
                    },
                    {
                      imageUrl:
                        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
                      name: "Cyndy Lillibridge",
                      rating: 3.0,
                      content:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
                      timeCreated: "3"
                    },
                    {
                      imageUrl:
                        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
                      name: "Georgette Strobel",
                      rating: 4.0,
                      content:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
                      timeCreated: "5"
                    }
                  ];
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <Reviews
                  data-plasmic-name={"reviews"}
                  data-plasmic-override={overrides.reviews}
                  className={classNames("__wab_instance", sty.reviews)}
                  content={(() => {
                    try {
                      return currentItem.content;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  createdAt={(() => {
                    try {
                      return currentItem.timeCreated;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  imageUrl={(() => {
                    try {
                      return currentItem.imageUrl;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  key={currentIndex}
                  name={(() => {
                    try {
                      return currentItem.name;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  rating={(() => {
                    try {
                      return currentItem.rating;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              );
            })}
            <div
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.button
              )}
            >
              {"Load More Reviews"}
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "main", "overallReview", "svg", "reviews", "button"],
  h1: ["h1"],
  main: ["main", "overallReview", "svg", "reviews", "button"],
  overallReview: ["overallReview", "svg"],
  svg: ["svg"],
  reviews: ["reviews"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    main: makeNodeComponent("main"),
    overallReview: makeNodeComponent("overallReview"),
    svg: makeNodeComponent("svg"),
    reviews: makeNodeComponent("reviews"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
