// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8ezVBUfhxTZRVwYwN3N5yL
// Component: nzUeeW99LIVl
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 8ezVBUfhxTZRVwYwN3N5yL/projectcss
import sty from "./PlasmicComponent2.module.css"; // plasmic-import: nzUeeW99LIVl/css

createPlasmicElementProxy;

export const PlasmicComponent2__VariantProps = new Array();

export const PlasmicComponent2__ArgProps = new Array("title", "smallTitle");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicComponent2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          title: "Hello",
          smallTitle: "Hello"
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"auto"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"100%"}
        loading={"lazy"}
        src={{
          src: "/plasmic/website_starter/images/heroImage.jpg",
          fullWidth: 4095,
          fullHeight: 2731,
          aspectRatio: undefined
        }}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return [
                {
                  index: 1
                },
                {
                  index: 2
                },
                {
                  index: 3
                },
                {
                  index: 4
                }
              ];
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__n1PRe
              )}
              key={currentIndex}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return "Hello user number " + currentItem.index;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Your Unique Wedding Experience.";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          );
        })}
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__eOm9G
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.title;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Embark on a Journey of Love and Luxury \u2013 Seamless Wedding Planning Tailored Just for You!";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "freeBox"],
  img: ["img"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicComponent2__ArgProps,
          internalVariantPropNames: PlasmicComponent2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicComponent2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComponent2";
  } else {
    func.displayName = `PlasmicComponent2.${nodeName}`;
  }
  return func;
}

export const PlasmicComponent2 = Object.assign(
  // Top-level PlasmicComponent2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicComponent2
    internalVariantProps: PlasmicComponent2__VariantProps,
    internalArgProps: PlasmicComponent2__ArgProps
  }
);

export default PlasmicComponent2;
/* prettier-ignore-end */
