// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8ezVBUfhxTZRVwYwN3N5yL
// Component: 0bDiwzUEHDAP
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Dialog from "../../Dialog"; // plasmic-import: IgWNcDVMzOb8/component
import Button from "../../Button"; // plasmic-import: Mk2LrAAMfItq/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdInputNumber } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Reviews from "../../Reviews"; // plasmic-import: vuK03WDG9KmD/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8ezVBUfhxTZRVwYwN3N5yL/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 0bDiwzUEHDAP/css
import Frame1000006008Icon from "./icons/PlasmicIcon__Frame1000006008"; // plasmic-import: 5gSvYEif6wmd/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("onClick");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "reviews",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            imageUrl:
              "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
            name: "Freida Varnes",
            rating: 5,
            content:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
            createdAt: "5"
          },
          {
            imageUrl:
              "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBvcnRyYWl0fGVufDB8fDB8fHww",
            name: "Marx Heshley",
            rating: 4,
            content:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
            createdAt: "4"
          },
          {
            imageUrl:
              "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
            name: "Cyndy Lillibridge",
            rating: 3,
            content:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
            createdAt: "3"
          },
          {
            imageUrl:
              "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cG9ydHJhaXR8ZW58MHx8MHx8fDA%3D",
            name: "Georgette Strobel",
            rating: 4,
            content:
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel suscipit ligula, et semper ligula. Donec lacinia, nunc posuere semper vehicula, nunc elit feugiat massa, in sodales lectus tortor scelerisque leo. Etiam mollis augue at tortor sagittis, ut semper nibh porta. Integer porttitor eros vel sodales consectetur. In eros sapien, feugiat in nibh at, gravida vulputate diam.",
            createdAt: "1"
          }
        ]
      },
      {
        path: "dialog.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <h1
            data-plasmic-name={"h1"}
            data-plasmic-override={overrides.h1}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.__wab_text,
              sty.h1
            )}
          >
            {"Reviews"}
          </h1>
          <section
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(projectcss.all, sty.main)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__roADe)}>
              <div
                data-plasmic-name={"overallReview"}
                data-plasmic-override={overrides.overallReview}
                className={classNames(projectcss.all, sty.overallReview)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jCWu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pH3Zd
                    )}
                  >
                    {"5.0"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__g8Os6)}
                  >
                    <Stack__
                      as={Frame1000006008Icon}
                      data-plasmic-name={"svg"}
                      data-plasmic-override={overrides.svg}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.svg)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p8Cxx
                      )}
                    >
                      {"1000 Reviews"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g6Cyh
                    )}
                  >
                    {"Very Good"}
                  </div>
                </div>
                <Dialog
                  data-plasmic-name={"dialog"}
                  data-plasmic-override={overrides.dialog}
                  body={(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.form),
                      extendedOnValuesChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["form", "value"],
                          FormWrapper_Helpers
                        ),
                      formItems: undefined,
                      labelCol: (() => {
                        const __composite = { span: 8, horizontalOnly: null };
                        __composite["horizontalOnly"] = true;
                        return __composite;
                      })(),
                      layout: "vertical",
                      mode: undefined,
                      onFinish: async values => {
                        const $steps = {};
                        $steps["updateReviews"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["reviews"]
                                },
                                operation: 5,
                                value: $state.form.value
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;
                                const arr = $stateGet(objRoot, variablePath);
                                arr.push(value);
                                return arr;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateReviews"] != null &&
                          typeof $steps["updateReviews"] === "object" &&
                          typeof $steps["updateReviews"].then === "function"
                        ) {
                          $steps["updateReviews"] = await $steps[
                            "updateReviews"
                          ];
                        }
                      },
                      onIsSubmittingChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "isSubmitting",
                          ["form", "isSubmitting"],
                          FormWrapper_Helpers
                        ),
                      ref: ref => {
                        $refs["form"] = ref;
                      },
                      wrapperCol: { span: 16, horizontalOnly: true }
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "form.value"
                        },
                        {
                          name: "isSubmitting",
                          plasmicStateName: "form.isSubmitting"
                        }
                      ],

                      [],
                      FormWrapper_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <FormWrapper
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        {...child$Props}
                      >
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__quOkH
                          )}
                          label={"Name"}
                          name={"name"}
                        >
                          <AntdInput
                            className={classNames(
                              "__wab_instance",
                              sty.input__eFqgW
                            )}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField___9Y0QZ
                          )}
                          initialValue={5}
                          label={"Rating"}
                          name={"rating"}
                        >
                          <AntdInputNumber
                            className={classNames(
                              "__wab_instance",
                              sty.numberInput
                            )}
                            type={"number"}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__lssSx
                          )}
                          label={"Review"}
                          name={"content"}
                        >
                          <AntdTextArea
                            className={classNames(
                              "__wab_instance",
                              sty.textArea
                            )}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField___6MRap
                          )}
                          hidden={true}
                          initialValue={"0"}
                          label={""}
                          name={"createdAt"}
                        >
                          <AntdInput
                            className={classNames(
                              "__wab_instance",
                              sty.input___5JqwK
                            )}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__bk79O
                          )}
                          hidden={true}
                          initialValue={
                            "https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg"
                          }
                          label={""}
                          name={"imageUrl"}
                        >
                          <AntdInput
                            className={classNames(
                              "__wab_instance",
                              sty.input__obekk
                            )}
                          />
                        </FormItemWrapper>
                        <AntdButton
                          className={classNames(
                            "__wab_instance",
                            sty.button___3Rj4W
                          )}
                          submitsForm={true}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xsaCy
                            )}
                          >
                            {"Submit"}
                          </div>
                        </AntdButton>
                      </FormWrapper>
                    );
                  })()}
                  className={classNames("__wab_instance", sty.dialog)}
                  onOpenChange={generateStateOnChangeProp($state, [
                    "dialog",
                    "open"
                  ])}
                  open={generateStateValueProp($state, ["dialog", "open"])}
                  title={"Write a review"}
                  trigger={
                    <Button color={"softSand"}>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qt7To
                        )}
                      >
                        {"Write a review"}
                      </div>
                    </Button>
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__nJwS)}>
                <div className={classNames(projectcss.all, sty.freeBox__b6UvF)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jRvNg)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a3JM
                      )}
                    >
                      {"Quality of Service\n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9EbHz
                      )}
                    >
                      {"5.0"}
                    </div>
                  </Stack__>
                  <section
                    className={classNames(projectcss.all, sty.section__pnSiU)}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__h8FCh)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jnK2J)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__trS5X
                      )}
                    >
                      {"Response Time"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p3QbO
                      )}
                    >
                      {"5.0"}
                    </div>
                  </Stack__>
                  <section
                    className={classNames(projectcss.all, sty.section__tVdcH)}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ipC8N)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cYs0B)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pD7D
                      )}
                    >
                      {"Professionalism"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qdKbO
                      )}
                    >
                      {"5.0"}
                    </div>
                  </Stack__>
                  <section
                    className={classNames(projectcss.all, sty.section__ojS2)}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9QtTn)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wW7M4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rAv7W
                      )}
                    >
                      {"Value"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dHmU
                      )}
                    >
                      {"5.0"}
                    </div>
                  </Stack__>
                  <section
                    className={classNames(projectcss.all, sty.section__us0H)}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___3NcJo)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__t78X2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__r905K
                      )}
                    >
                      {"Flexibility"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__o2RUr
                      )}
                    >
                      {"5.0"}
                    </div>
                  </Stack__>
                  <section
                    className={classNames(projectcss.all, sty.section__xT0Pq)}
                  />
                </div>
              </div>
            </div>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $state.reviews;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <Reviews
                  data-plasmic-name={"reviews"}
                  data-plasmic-override={overrides.reviews}
                  className={classNames("__wab_instance", sty.reviews)}
                  content={(() => {
                    try {
                      return currentItem.content;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  createdAt={(() => {
                    try {
                      return currentItem.createdAt;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  imageUrl={(() => {
                    try {
                      return currentItem.imageUrl;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  key={currentIndex}
                  name={(() => {
                    try {
                      return currentItem.name;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  rating={(() => {
                    try {
                      return currentItem.rating;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              );
            })}
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__j8QRn
              )}
            >
              {"Load More Reviews"}
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "main",
    "overallReview",
    "svg",
    "dialog",
    "form",
    "numberInput",
    "textArea",
    "reviews"
  ],

  h1: ["h1"],
  main: [
    "main",
    "overallReview",
    "svg",
    "dialog",
    "form",
    "numberInput",
    "textArea",
    "reviews"
  ],

  overallReview: [
    "overallReview",
    "svg",
    "dialog",
    "form",
    "numberInput",
    "textArea"
  ],

  svg: ["svg"],
  dialog: ["dialog", "form", "numberInput", "textArea"],
  form: ["form", "numberInput", "textArea"],
  numberInput: ["numberInput"],
  textArea: ["textArea"],
  reviews: ["reviews"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    main: makeNodeComponent("main"),
    overallReview: makeNodeComponent("overallReview"),
    svg: makeNodeComponent("svg"),
    dialog: makeNodeComponent("dialog"),
    form: makeNodeComponent("form"),
    numberInput: makeNodeComponent("numberInput"),
    textArea: makeNodeComponent("textArea"),
    reviews: makeNodeComponent("reviews"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
